name: CI/CD
on: [push]

jobs:
  pipelines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Build the Docker Image
      run: docker build -t hello-site .
    - name: Test the running container
      run: |
        docker run -d -p 8080:80 hello-site
        sleep 2
        curl -s http://localhost:8080 | grep "Hello"
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push the SAME tested image
      run: |
          docker tag hello-site ${{ secrets.DOCKERHUB_USERNAME }}/hello-site
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-site
